In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', 50)

In [2]:
data_folder = '../Data/Training/pickle_data'
exclude_features = ['TIMESTAMP', 'pit_number', 'Redox_error_flag']

## 2022 data

In [3]:
# Get train and test data for 2022
# Train X
folder = f'{data_folder}/2022/X_train.pkl'
train_X = pd.read_pickle(open(folder, 'rb'))
train_X = train_X.loc[:,~train_X.columns.isin(exclude_features)]
# Test X
folder = f'{data_folder}/2022/X_test.pkl'
test_X = pd.read_pickle(open(folder, 'rb'))
test_X = test_X.loc[:,~test_X.columns.isin(exclude_features)]
# Train y
folder = f'{data_folder}/2022/y_train.pkl'
train_y = pd.read_pickle(open(folder, 'rb'))

### Feature selection

In [4]:
selector = SelectKBest(f_classif, k=10)
selector.fit(train_X, np.ravel(train_y))

print('Number of input features: ', selector.n_features_in_)

feature_scores = {'Input features Names': list(selector.feature_names_in_),
                  'Input features scores': list(selector.scores_),
                  'Input features pvalues': list(selector.pvalues_)}

df = pd.DataFrame(feature_scores)
df.sort_values(by=['Input features scores'], ascending=False, inplace=True)

print('Top 10 features Names:\n\t', list(selector.get_feature_names_out()))

df

Number of input features:  48
Top 10 features Names:
	 ['Redox_Avg(2)_sigma_b_24', 'Redox_Avg(2)_sigma_f_24', 'Redox_Avg(3)_sigma_b_24', 'Redox_Avg(3)_sigma_f_24', 'Redox_Avg(4)_sigma_b_24', 'Redox_Avg(4)_sigma_f_24', 'Redox_Avg(5)_sigma_b_24', 'Redox_Avg(5)_sigma_f_24', 'Redox_Avg(3)_sigma_f_12', 'Redox_Avg(4)_sigma_b_12']

       Input features Names  Input features scores  Input features pvalues
36  Redox_Avg(5)_sigma_b_24           37785.759810            0.000000e+00
34  Redox_Avg(4)_sigma_b_24           37514.940848            0.000000e+00
37  Redox_Avg(5)_sigma_f_24           36051.098122            0.000000e+00
35  Redox_Avg(4)_sigma_f_24           35833.798843            0.000000e+00
32  Redox_Avg(3)_sigma_b_24           35499.949963            0.000000e+00
33  Redox_Avg(3)_sigma_f_24           34869.160166            0.000000e+00
31  Redox_Avg(2)_sigma_f_24           32303.661227            0.000000e+00
30  Redox_Avg(2)_sigma_b_24           30880.686566            0.000000e+00
44  Redox_Avg(4)_sigma_b_12           29524.169100            0.000000e+00
43  Redox_Avg(3)_sigma_f_12           29488.149863            0.000000e+00
42  Redox_Avg(3)_sigma_b_12           29372.650393            0.000000e+00
45  Redox_Avg(4)_sigma_f_12           28993.701297            0.000000e+00
46  Redox_Avg(5)_sigma_b_12           28935.228681            0.000000e+00
41  Redox_Avg(2)_sigma_f_12           28610.689527            0.000000e+00
47  Redox_Avg(5)_sigma_f_12           28459.880133            0.000000e+00
40  Redox_Avg(2)_sigma_b_12           26961.665039            0.000000e+00
1              Redox_Avg(2)           23433.765225            0.000000e+00
28  Redox_Avg(1)_sigma_b_24           18954.134567            0.000000e+00
38  Redox_Avg(1)_sigma_b_12           18401.137708            0.000000e+00
39  Redox_Avg(1)_sigma_f_12           15977.081308            0.000000e+00
29  Redox_Avg(1)_sigma_f_24           14743.966497            0.000000e+00
20          Water_level_Avg           12419.345558            0.000000e+00
0              Redox_Avg(1)           11948.900549            0.000000e+00
23                      WC1           10545.141370            0.000000e+00
27                      WC5            7417.736448            0.000000e+00
22            BatterymV_Min            6833.546186            0.000000e+00
14                EC_Avg(5)            4941.956136            0.000000e+00
15  Matric_potential_Avg(1)            4516.366122            0.000000e+00
19  Matric_potential_Avg(5)            4051.378508            0.000000e+00
21          Temp_ottpls_Avg            3236.152214            0.000000e+00
2              Redox_Avg(3)            3099.415461            0.000000e+00
16  Matric_potential_Avg(2)            2623.717912            0.000000e+00
5           Temp_T12_Avg(1)            2304.713918            0.000000e+00
12                EC_Avg(4)            1868.917452            0.000000e+00
17  Matric_potential_Avg(3)            1764.837164            0.000000e+00
8                 EC_Avg(2)            1426.830159           5.954595e-310
3              Redox_Avg(4)            1003.045060           5.301513e-219
7           Temp_T12_Avg(2)             871.960072           8.789666e-191
26                      WC4             728.816490           6.438412e-160
24                      WC2             439.819472            1.962416e-97
10                EC_Avg(3)             429.024342            4.282659e-95
6                 EC_Avg(1)             351.841198            2.326072e-78
9           Temp_T12_Avg(3)             311.169030            1.564986e-69
4              Redox_Avg(5)             250.495283            2.387021e-56
13          Temp_T12_Avg(5)             205.351674            1.585363e-46
25                      WC3             153.428006            3.286008e-35
18  Matric_potential_Avg(4)             103.123546            3.238933e-24
11          Temp_T12_Avg(4)               4.381310            3.633768e-02

## 2022_sensors data

In [5]:
sensor_data = dict()

# Get train and test data for 2022_sensors
for sensor in range(1,6):
    features = [f'Redox_Avg({sensor})', f'EC_Avg({sensor})', f'Matric_potential_Avg({sensor})', f'Temp_T12_Avg({sensor})',
                    'Water_level_Avg', 'Temp_ottpls_Avg', 'BatterymV_Min', f'WC{sensor}',
                    f'Redox_Avg({sensor})_sigma_b_24', f'Redox_Avg({sensor})_sigma_f_24',
                    f'Redox_Avg({sensor})_sigma_b_12', f'Redox_Avg({sensor})_sigma_f_12']

    # Train X
    folder = f'{data_folder}/2022_sensors/X_train_sensor_{sensor}.pkl'
    train_X = pd.read_pickle(open(folder, 'rb'))
    train_X = train_X.loc[:,features]
    # Test X
    folder = f'{data_folder}/2022_sensors/X_test_sensor_{sensor}.pkl'
    test_X = pd.read_pickle(open(folder, 'rb'))
    test_X = test_X.loc[:,features]
    # Train y
    folder = f'{data_folder}/2022_sensors/y_train_sensor_{sensor}.pkl'
    train_y = pd.read_pickle(open(folder, 'rb'))

    sensor_data[f'train_X_{sensor}'] = train_X
    sensor_data[f'tets_X_{sensor}'] = test_X
    sensor_data[f'train_y_{sensor}'] = train_y

### Sensor 1

In [6]:
train_X = sensor_data['train_X_1']
train_y = sensor_data['train_y_1']

selector = SelectKBest(f_classif, k=10)
selector.fit(train_X, np.ravel(train_y))

print('Number of input features: ', selector.n_features_in_)

feature_scores = {'Input features Names': list(selector.feature_names_in_),
                  'Input features scores': list(selector.scores_),
                  'Input features pvalues': list(selector.pvalues_)}

df = pd.DataFrame(feature_scores)
df.sort_values(by=['Input features scores'], ascending=False, inplace=True)

print('Top 10 features Names:\n\t', list(selector.get_feature_names_out()))

df

Number of input features:  12
Top 10 features Names:
	 ['EC_Avg(1)', 'Matric_potential_Avg(1)', 'Water_level_Avg', 'Temp_ottpls_Avg', 'BatterymV_Min', 'WC1', 'Redox_Avg(1)_sigma_b_24', 'Redox_Avg(1)_sigma_f_24', 'Redox_Avg(1)_sigma_b_12', 'Redox_Avg(1)_sigma_f_12']

       Input features Names  Input features scores  Input features pvalues
8   Redox_Avg(1)_sigma_b_24            4495.239340            0.000000e+00
11  Redox_Avg(1)_sigma_f_12            3911.708658            0.000000e+00
9   Redox_Avg(1)_sigma_f_24            3778.678981            0.000000e+00
10  Redox_Avg(1)_sigma_b_12            3770.282760            0.000000e+00
1                 EC_Avg(1)            3548.809454            0.000000e+00
4           Water_level_Avg            3476.641388            0.000000e+00
5           Temp_ottpls_Avg            1595.607131            0.000000e+00
2   Matric_potential_Avg(1)             850.799652           3.186549e-186
6             BatterymV_Min             793.680170           6.550520e-174
7                       WC1             320.564813            1.427359e-71
3           Temp_T12_Avg(1)              58.427099            2.129119e-14
0              Redox_Avg(1)               8.285932            3.996220e-03

### Sensor 2

In [7]:
train_X = sensor_data['train_X_2']
train_y = sensor_data['train_y_2']

selector = SelectKBest(f_classif, k=10)
selector.fit(train_X, np.ravel(train_y))

print('Number of input features: ', selector.n_features_in_)

feature_scores = {'Input features Names': list(selector.feature_names_in_),
                  'Input features scores': list(selector.scores_),
                  'Input features pvalues': list(selector.pvalues_)}

df = pd.DataFrame(feature_scores)
df.sort_values(by=['Input features scores'], ascending=False, inplace=True)

print('Top 10 features Names:\n\t', list(selector.get_feature_names_out()))

df

Number of input features:  12
Top 10 features Names:
	 ['Redox_Avg(2)', 'EC_Avg(2)', 'Matric_potential_Avg(2)', 'Water_level_Avg', 'Temp_ottpls_Avg', 'BatterymV_Min', 'Redox_Avg(2)_sigma_b_24', 'Redox_Avg(2)_sigma_f_24', 'Redox_Avg(2)_sigma_b_12', 'Redox_Avg(2)_sigma_f_12']

       Input features Names  Input features scores  Input features pvalues
9   Redox_Avg(2)_sigma_f_24           32418.505639            0.000000e+00
8   Redox_Avg(2)_sigma_b_24           30883.173054            0.000000e+00
11  Redox_Avg(2)_sigma_f_12           28562.323056            0.000000e+00
10  Redox_Avg(2)_sigma_b_12           27132.647302            0.000000e+00
0              Redox_Avg(2)           23616.452709            0.000000e+00
4           Water_level_Avg           12407.256341            0.000000e+00
6             BatterymV_Min            6819.797537            0.000000e+00
5           Temp_ottpls_Avg            3224.664039            0.000000e+00
2   Matric_potential_Avg(2)            2619.342862            0.000000e+00
1                 EC_Avg(2)            1417.654918           5.489453e-308
3           Temp_T12_Avg(2)             873.325565           4.464716e-191
7                       WC2             437.890136            5.137843e-97

### Sensor 3

In [8]:
train_X = sensor_data['train_X_3']
train_y = sensor_data['train_y_3']

selector = SelectKBest(f_classif, k=10)
selector.fit(train_X, np.ravel(train_y))

print('Number of input features: ', selector.n_features_in_)

feature_scores = {'Input features Names': list(selector.feature_names_in_),
                  'Input features scores': list(selector.scores_),
                  'Input features pvalues': list(selector.pvalues_)}

df = pd.DataFrame(feature_scores)
df.sort_values(by=['Input features scores'], ascending=False, inplace=True)

print('Top 10 features Names:\n\t', list(selector.get_feature_names_out()))

df

Number of input features:  12
Top 10 features Names:
	 ['Redox_Avg(3)', 'EC_Avg(3)', 'Matric_potential_Avg(3)', 'Water_level_Avg', 'Temp_ottpls_Avg', 'BatterymV_Min', 'Redox_Avg(3)_sigma_b_24', 'Redox_Avg(3)_sigma_f_24', 'Redox_Avg(3)_sigma_b_12', 'Redox_Avg(3)_sigma_f_12']

       Input features Names  Input features scores  Input features pvalues
8   Redox_Avg(3)_sigma_b_24           35499.949963            0.000000e+00
9   Redox_Avg(3)_sigma_f_24           34869.160166            0.000000e+00
11  Redox_Avg(3)_sigma_f_12           29488.149863            0.000000e+00
10  Redox_Avg(3)_sigma_b_12           29372.650393            0.000000e+00
4           Water_level_Avg           12419.345558            0.000000e+00
6             BatterymV_Min            6833.546186            0.000000e+00
5           Temp_ottpls_Avg            3236.152214            0.000000e+00
0              Redox_Avg(3)            3099.415461            0.000000e+00
2   Matric_potential_Avg(3)            1764.837164            0.000000e+00
1                 EC_Avg(3)             429.024342            4.282659e-95
3           Temp_T12_Avg(3)             311.169030            1.564986e-69
7                       WC3             153.428006            3.286008e-35

### Sensor 4

In [9]:
train_X = sensor_data['train_X_4']
train_y = sensor_data['train_y_4']

selector = SelectKBest(f_classif, k=10)
selector.fit(train_X, np.ravel(train_y))

print('Number of input features: ', selector.n_features_in_)

feature_scores = {'Input features Names': list(selector.feature_names_in_),
                  'Input features scores': list(selector.scores_),
                  'Input features pvalues': list(selector.pvalues_)}

df = pd.DataFrame(feature_scores)
df.sort_values(by=['Input features scores'], ascending=False, inplace=True)

print('Top 10 features Names:\n\t', list(selector.get_feature_names_out()))

df

Number of input features:  12
Top 10 features Names:
	 ['Redox_Avg(4)', 'EC_Avg(4)', 'Water_level_Avg', 'Temp_ottpls_Avg', 'BatterymV_Min', 'WC4', 'Redox_Avg(4)_sigma_b_24', 'Redox_Avg(4)_sigma_f_24', 'Redox_Avg(4)_sigma_b_12', 'Redox_Avg(4)_sigma_f_12']

       Input features Names  Input features scores  Input features pvalues
8   Redox_Avg(4)_sigma_b_24           37514.940848            0.000000e+00
9   Redox_Avg(4)_sigma_f_24           35833.798843            0.000000e+00
10  Redox_Avg(4)_sigma_b_12           29524.169100            0.000000e+00
11  Redox_Avg(4)_sigma_f_12           28993.701297            0.000000e+00
4           Water_level_Avg           12419.345558            0.000000e+00
6             BatterymV_Min            6833.546186            0.000000e+00
5           Temp_ottpls_Avg            3236.152214            0.000000e+00
1                 EC_Avg(4)            1868.917452            0.000000e+00
0              Redox_Avg(4)            1003.045060           5.301513e-219
7                       WC4             728.816490           6.438412e-160
2   Matric_potential_Avg(4)             103.123546            3.238933e-24
3           Temp_T12_Avg(4)               4.381310            3.633768e-02

### Sensor 5

In [10]:
train_X = sensor_data['train_X_5']
train_y = sensor_data['train_y_5']

selector = SelectKBest(f_classif, k=10)
selector.fit(train_X, np.ravel(train_y))

print('Number of input features: ', selector.n_features_in_)

feature_scores = {'Input features Names': list(selector.feature_names_in_),
                  'Input features scores': list(selector.scores_),
                  'Input features pvalues': list(selector.pvalues_)}

df = pd.DataFrame(feature_scores)
df.sort_values(by=['Input features scores'], ascending=False, inplace=True)

print('Top 10 features Names:\n\t', list(selector.get_feature_names_out()))

df

Number of input features:  12
Top 10 features Names:
	 ['EC_Avg(5)', 'Matric_potential_Avg(5)', 'Water_level_Avg', 'Temp_ottpls_Avg', 'BatterymV_Min', 'WC5', 'Redox_Avg(5)_sigma_b_24', 'Redox_Avg(5)_sigma_f_24', 'Redox_Avg(5)_sigma_b_12', 'Redox_Avg(5)_sigma_f_12']

       Input features Names  Input features scores  Input features pvalues
8   Redox_Avg(5)_sigma_b_24           37785.759810            0.000000e+00
9   Redox_Avg(5)_sigma_f_24           36051.098122            0.000000e+00
10  Redox_Avg(5)_sigma_b_12           28935.228681            0.000000e+00
11  Redox_Avg(5)_sigma_f_12           28459.880133            0.000000e+00
4           Water_level_Avg           12419.345558            0.000000e+00
7                       WC5            7417.736448            0.000000e+00
6             BatterymV_Min            6833.546186            0.000000e+00
1                 EC_Avg(5)            4941.956136            0.000000e+00
2   Matric_potential_Avg(5)            4051.378508            0.000000e+00
5           Temp_ottpls_Avg            3236.152214            0.000000e+00
0              Redox_Avg(5)             250.495283            2.387021e-56
3           Temp_T12_Avg(5)             205.351674            1.585363e-46

# Initial results

In [4]:
results_csv = pd.read_csv('./pack/Results.csv')
results_1_csv = pd.read_csv('./pack/Results_1.csv')

In [16]:
list(results_csv.columns.array)

['Unnamed: 0',
 'mean_fit_time',
 'std_fit_time',
 'mean_score_time',
 'std_score_time',
 'param_C',
 'param_degree',
 'params',
 'split0_test_score',
 'split1_test_score',
 'split2_test_score',
 'split3_test_score',
 'split4_test_score',
 'split5_test_score',
 'split6_test_score',
 'split7_test_score',
 'split8_test_score',
 'split9_test_score',
 'mean_test_score',
 'std_test_score',
 'rank_test_score',
 'split0_train_score',
 'split1_train_score',
 'split2_train_score',
 'split3_train_score',
 'split4_train_score',
 'split5_train_score',
 'split6_train_score',
 'split7_train_score',
 'split8_train_score',
 'split9_train_score',
 'mean_train_score',
 'std_train_score']

In [20]:
# 'mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time', 'params', 'mean_test_score', 'std_test_score', 'rank_test_score', 'mean_train_score'
results_csv.sort_values(by=['rank_test_score']).loc[:, ['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time', 'params', 'mean_test_score', 'std_test_score', 'rank_test_score', 'mean_train_score']]

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,params,mean_test_score,std_test_score,rank_test_score,mean_train_score
32,39.147348,60.206797,0.697735,0.063821,"{'C': 6, 'degree': 5}",0.999891,0.000123,1,0.999913
37,16.884655,1.032047,0.628651,0.036295,"{'C': 7, 'degree': 5}",0.999883,0.000118,2,0.999913
27,20.478305,1.665030,0.795193,0.060853,"{'C': 5, 'degree': 5}",0.999876,0.000126,3,0.999897
38,20.077468,1.637983,0.731186,0.035285,"{'C': 7, 'degree': 6}",0.999876,0.000098,4,0.999900
36,16.776244,0.952237,0.606928,0.048837,"{'C': 7, 'degree': 4}",0.999869,0.000125,5,0.999893
31,18.846284,1.011086,0.644017,0.035454,"{'C': 6, 'degree': 4}",0.999861,0.000124,6,0.999879
26,20.658843,1.531004,0.722552,0.037715,"{'C': 5, 'degree': 4}",0.999840,0.000130,7,0.999867
33,21.550211,1.238632,0.808091,0.034756,"{'C': 6, 'degree': 6}",0.999796,0.000085,8,0.999828
35,18.319232,1.641818,0.623619,0.028464,"{'C': 7, 'degree': 3}",0.999789,0.000147,9,0.999802
30,19.751010,0.722692,0.702813,0.057918,"{'C': 6, 'degree': 3}",0.999781,0.000142,10,0.999793
25,21.786308,1.277237,0.749818,0.037401,"{'C': 5, 'degree': 3}",0.999781,0.000142,10,0.999779
21,23.854393,1.694255,0.854396,0.036362,"{'C': 4, 'degree': 4}",0.999774,0.000132,12,0.999797
20,23.549945,1.452253,0.884148,0.054781,"{'C': 4, 'degree': 3}",0.999679,0.000207,13,0.999705
22,23.741659,2.053051,0.955561,0.064633,"{'C': 4, 'degree': 5}",0.999650,0.000190,14,0.999704
28,24.965995,1.584941,0.920109,0.040378,"{'C': 5, 'degree': 6}",0.999650,0.000152,15,0.999695
39,24.398249,1.568210,0.943095,0.064857,"{'C': 7, 'degree': 7}",0.999636,0.000153,16,0.999695
34,27.607914,1.996575,1.090624,0.077033,"{'C': 6, 'degree': 7}",0.999446,0.000179,17,0.999494
23,29.141170,1.957357,1.098414,0.057650,"{'C': 4, 'degree': 6}",0.999402,0.000187,18,0.999430
29,30.714465,1.856015,1.222225,0.071696,"{'C': 5, 'degree': 7}",0.999366,0.000170,19,0.999414
16,28.711027,2.131858,1.056837,0.070437,"{'C': 3, 'degree': 4}",0.999205,0.000241,20,0.999248
17,30.403869,1.630455,1.136287,0.074612,"{'C': 3, 'degree': 5}",0.999169,0.000236,21,0.999228
24,35.274028,1.988719,1.430551,0.111996,"{'C': 4, 'degree': 7}",0.999118,0.000225,22,0.999200
18,35.022414,2.323916,1.375753,0.083819,"{'C': 3, 'degree': 6}",0.999009,0.000229,23,0.999043
19,43.254447,3.358309,1.771647,0.114886,"{'C': 3, 'degree': 7}",0.998899,0.000234,24,0.998960
14,53.378580,4.090819,2.415537,0.178852,"{'C': 2, 'degree': 7}",0.998870,0.000229,25,0.998920
13,44.119249,3.324582,1.826957,0.091081,"{'C': 2, 'degree': 6}",0.998870,0.000219,25,0.998907
11,34.761426,1.871943,1.322791,0.089042,"{'C': 2, 'degree': 4}",0.998834,0.000211,27,0.998842
12,37.162348,3.147819,1.525266,0.124028,"{'C': 2, 'degree': 5}",0.998834,0.000206,28,0.998860
7,113.618548,185.685392,2.346227,0.174031,"{'C': 1, 'degree': 5}",0.998804,0.000226,29,0.998825
8,60.072576,2.720219,2.798022,0.184920,"{'C': 1, 'degree': 6}",0.998724,0.000236,30,0.998761
15,44.194359,47.601969,1.039196,0.077441,"{'C': 3, 'degree': 3}",0.998542,0.000347,31,0.998573
10,32.968199,1.586480,1.298272,0.092806,"{'C': 2, 'degree': 3}",0.998462,0.000310,32,0.998462
9,70.891120,3.094743,3.704000,0.273233,"{'C': 1, 'degree': 7}",0.998455,0.000321,33,0.998519
6,47.053764,1.897289,2.123878,0.199469,"{'C': 1, 'degree': 4}",0.998440,0.000321,34,0.998461
5,48.628116,2.581197,1.998692,0.131810,"{'C': 1, 'degree': 3}",0.998418,0.000365,35,0.998409
1,73.328257,4.435705,3.240716,0.319097,"{'C': 0.5, 'degree': 4}",0.998374,0.000345,36,0.998373
0,154.693949,158.664523,3.133404,0.245709,"{'C': 0.5, 'degree': 3}",0.998345,0.000354,37,0.998365
2,82.955641,3.638400,3.711509,0.315416,"{'C': 0.5, 'degree': 5}",0.998258,0.000361,38,0.998288
3,89.991873,4.544386,4.574949,0.477173,"{'C': 0.5, 'degree': 6}",0.997981,0.000391,39,0.998004
4,128.439196,76.553469,6.132092,0.760513,"{'C': 0.5, 'degree': 7}",0.997259,0.000368,40,0.997299

In [18]:
results_csv.sort_values(by=['rank_test_score']).loc[:, ['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time', 'params', 'mean_test_score', 'std_test_score', 'rank_test_score', 'mean_train_score']]

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,params,mean_test_score,std_test_score,rank_test_score,mean_train_score
32,39.147348,60.206797,0.697735,0.063821,"{'C': 6, 'degree': 5}",0.999891,0.000123,1,0.999913
37,16.884655,1.032047,0.628651,0.036295,"{'C': 7, 'degree': 5}",0.999883,0.000118,2,0.999913
27,20.478305,1.665030,0.795193,0.060853,"{'C': 5, 'degree': 5}",0.999876,0.000126,3,0.999897
38,20.077468,1.637983,0.731186,0.035285,"{'C': 7, 'degree': 6}",0.999876,0.000098,4,0.999900
36,16.776244,0.952237,0.606928,0.048837,"{'C': 7, 'degree': 4}",0.999869,0.000125,5,0.999893
31,18.846284,1.011086,0.644017,0.035454,"{'C': 6, 'degree': 4}",0.999861,0.000124,6,0.999879
26,20.658843,1.531004,0.722552,0.037715,"{'C': 5, 'degree': 4}",0.999840,0.000130,7,0.999867
33,21.550211,1.238632,0.808091,0.034756,"{'C': 6, 'degree': 6}",0.999796,0.000085,8,0.999828
35,18.319232,1.641818,0.623619,0.028464,"{'C': 7, 'degree': 3}",0.999789,0.000147,9,0.999802
30,19.751010,0.722692,0.702813,0.057918,"{'C': 6, 'degree': 3}",0.999781,0.000142,10,0.999793
25,21.786308,1.277237,0.749818,0.037401,"{'C': 5, 'degree': 3}",0.999781,0.000142,10,0.999779
21,23.854393,1.694255,0.854396,0.036362,"{'C': 4, 'degree': 4}",0.999774,0.000132,12,0.999797
20,23.549945,1.452253,0.884148,0.054781,"{'C': 4, 'degree': 3}",0.999679,0.000207,13,0.999705
22,23.741659,2.053051,0.955561,0.064633,"{'C': 4, 'degree': 5}",0.999650,0.000190,14,0.999704
28,24.965995,1.584941,0.920109,0.040378,"{'C': 5, 'degree': 6}",0.999650,0.000152,15,0.999695
39,24.398249,1.568210,0.943095,0.064857,"{'C': 7, 'degree': 7}",0.999636,0.000153,16,0.999695
34,27.607914,1.996575,1.090624,0.077033,"{'C': 6, 'degree': 7}",0.999446,0.000179,17,0.999494
23,29.141170,1.957357,1.098414,0.057650,"{'C': 4, 'degree': 6}",0.999402,0.000187,18,0.999430
29,30.714465,1.856015,1.222225,0.071696,"{'C': 5, 'degree': 7}",0.999366,0.000170,19,0.999414
16,28.711027,2.131858,1.056837,0.070437,"{'C': 3, 'degree': 4}",0.999205,0.000241,20,0.999248
17,30.403869,1.630455,1.136287,0.074612,"{'C': 3, 'degree': 5}",0.999169,0.000236,21,0.999228
24,35.274028,1.988719,1.430551,0.111996,"{'C': 4, 'degree': 7}",0.999118,0.000225,22,0.999200
18,35.022414,2.323916,1.375753,0.083819,"{'C': 3, 'degree': 6}",0.999009,0.000229,23,0.999043
19,43.254447,3.358309,1.771647,0.114886,"{'C': 3, 'degree': 7}",0.998899,0.000234,24,0.998960
14,53.378580,4.090819,2.415537,0.178852,"{'C': 2, 'degree': 7}",0.998870,0.000229,25,0.998920
13,44.119249,3.324582,1.826957,0.091081,"{'C': 2, 'degree': 6}",0.998870,0.000219,25,0.998907
11,34.761426,1.871943,1.322791,0.089042,"{'C': 2, 'degree': 4}",0.998834,0.000211,27,0.998842
12,37.162348,3.147819,1.525266,0.124028,"{'C': 2, 'degree': 5}",0.998834,0.000206,28,0.998860
7,113.618548,185.685392,2.346227,0.174031,"{'C': 1, 'degree': 5}",0.998804,0.000226,29,0.998825
8,60.072576,2.720219,2.798022,0.184920,"{'C': 1, 'degree': 6}",0.998724,0.000236,30,0.998761
15,44.194359,47.601969,1.039196,0.077441,"{'C': 3, 'degree': 3}",0.998542,0.000347,31,0.998573
10,32.968199,1.586480,1.298272,0.092806,"{'C': 2, 'degree': 3}",0.998462,0.000310,32,0.998462
9,70.891120,3.094743,3.704000,0.273233,"{'C': 1, 'degree': 7}",0.998455,0.000321,33,0.998519
6,47.053764,1.897289,2.123878,0.199469,"{'C': 1, 'degree': 4}",0.998440,0.000321,34,0.998461
5,48.628116,2.581197,1.998692,0.131810,"{'C': 1, 'degree': 3}",0.998418,0.000365,35,0.998409
1,73.328257,4.435705,3.240716,0.319097,"{'C': 0.5, 'degree': 4}",0.998374,0.000345,36,0.998373
0,154.693949,158.664523,3.133404,0.245709,"{'C': 0.5, 'degree': 3}",0.998345,0.000354,37,0.998365
2,82.955641,3.638400,3.711509,0.315416,"{'C': 0.5, 'degree': 5}",0.998258,0.000361,38,0.998288
3,89.991873,4.544386,4.574949,0.477173,"{'C': 0.5, 'degree': 6}",0.997981,0.000391,39,0.998004
4,128.439196,76.553469,6.132092,0.760513,"{'C': 0.5, 'degree': 7}",0.997259,0.000368,40,0.997299